language: java

notifications:
  slack: thoughtworksarts:RdQaWk8I3BpwUpyw7Dyri2Hj

jdk:
  - oraclejdk8

cache:
    directories:
     - $HOME/.gradle/caches/
     - $HOME/.gradle/wrapper/
     - asio/
     - src/main/resources/video/
     - src/main/resources/audio/

install: travis_wait 30 ./gradlew assemble

script:
  - travis_wait 30 ./gradlew test