language: java

notifications:
  slack: thoughtworksarts:koNU6SlW5pDN8TRB5GyDSiaS

jdk:
  - openjdk12

cache:
    directories:
     - $HOME/.gradle/caches/
     - $HOME/.gradle/wrapper/
     - asio/
     - src/main/resources/video/
     - src/main/resources/audio/

install: travis_wait 30 ./gradlew assemble

script:
  - travis_wait 30 ./gradlew test
