language: java

jdk:
  - oraclejdk8

cache:
    directories:
     - .gradle/
     - $HOME/.gradle/caches/
     - $HOME/.gradle/wrapper/
     - asio/
     - src/main/resources/video/
     - src/main/resources/audio/

script:
  - travis_wait 30 ./gradlew clean test